services:
  - type: web
    name: pakshiai-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn app:app -w 4 -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
