// Comprehensive Indian Bird Species Database (80+ Species)
// Each bird includes research metadata, conservation status and a stable sound URL (Xeno-canto/Wikimedia)

export const indianBirds = [
        {
                id: 1,
                commonName: "Indian Peacock",
                scientificName: "Pavo cristatus",
                family: "Phasianidae",
                order: "Galliformes",
                conservationStatus: "N/A",
                habitat: ["Forest", "Scrub", "Agricultural"],
                migration: "Resident",
                description: "India's national bird. Males display spectacular iridescent blue-green tail feathers with eye-spots during elaborate courtship dances.",
                soundProfile: { clarity: "High", dominantFreq: "0.3-3 kHz", callPattern: "Loud, repeated 'may-awe' call, especially during monsoon", noiseLevel: "Low ambient required", bestTime: "Dawn & Dusk" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Indian%20Peacock/ML100366891.jpg`,
                soundUrl: "https://xeno-canto.org/sounds/uploaded/NWTKEXMKCA/XC1085991-Blue-Peafowl_Sultanpur1.mp3",
                callTypes: ["song", "alarm", "contact"],
                researchDOI: "10.1007/s10336-011-0705-7",
                soibPriority: "Low",
                longTermTrend: "Strong Increase"
        },
        {
                id: 2,
                commonName: "House Crow",
                scientificName: "Corvus splendens",
                family: "Corvidae",
                order: "Passeriformes",
                conservationStatus: "N/A",
                habitat: ["Urban", "Agricultural"],
                migration: "Resident",
                description: "Highly adaptable corvid found in all Indian cities. Known for remarkable intelligence and problem-solving abilities.",
                soundProfile: { clarity: "Medium", dominantFreq: "0.5-4 kHz", callPattern: "Harsh 'kaa-kaa' calls, variety of context-specific vocalizations", noiseLevel: "Tolerant of urban noise", bestTime: "All day" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/House%20Crow/ML100356141.jpg`,
                soundUrl: "https://xeno-canto.org/sounds/uploaded/NXHTMHMNSS/XC991526-250403_2781-House-Crow-20250403-6.56am-Andaman-Zone-Hotel-area-xeno.mp3",
                callTypes: ["call", "alarm"],
                frequencyRange: "0.5-4 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.1093/beheco/arq047",
                soibPriority: "Low",
                longTermTrend: "Moderate Increase"
        },
        {
                id: 3,
                commonName: "Purple Sunbird",
                scientificName: "Cinnyris asiaticus",
                family: "Nectariniidae",
                order: "Passeriformes",
                conservationStatus: "N/A",
                habitat: ["Gardens", "Forest", "Scrub"],
                migration: "Resident",
                description: "Small, active nectar-feeding bird. Breeding males display stunning metallic purple-blue iridescent plumage.",
                soundProfile: { clarity: "Very High", dominantFreq: "2-8 kHz", callPattern: "Rapid, high-pitched 'cheewit' notes and tinkling song", noiseLevel: "Sensitive to noise", bestTime: "Morning" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Purple%20Sunbird/main.png`,
                soundUrl: "https://xeno-canto.org/1054123/download",
                callTypes: ["song", "call"],
                frequencyRange: "2-8 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.2307/4089027",
                soibPriority: "Low",
                longTermTrend: "Stable"
        },
        {
                id: 4,
                commonName: "Red-vented Bulbul",
                scientificName: "Pycnonotus cafer",
                family: "Pycnonotidae",
                order: "Passeriformes",
                conservationStatus: "N/A",
                habitat: ["Gardens", "Forest", "Urban"],
                migration: "Resident",
                description: "Widespread bird with a distinctive red vent patch and jaunty black crest. Cheerful song is a common garden soundtrack.",
                soundProfile: { clarity: "High", dominantFreq: "1-6 kHz", callPattern: "Melodious whistling 'be-careful-be-careful' song", noiseLevel: "Moderate tolerance", bestTime: "Dawn" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Red-vented%20Bulbul/main.png`,
                soundUrl: "https://xeno-canto.org/876447/download",
                callTypes: ["song", "call", "alarm"],
                frequencyRange: "1-6 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.1111/ibi.12142",
                soibPriority: "Low",
                longTermTrend: "Stable"
        },
        {
                id: 5,
                commonName: "Asian Koel",
                scientificName: "Eudynamys scolopaceus",
                family: "Cuculidae",
                order: "Cuculiformes",
                conservationStatus: "N/A",
                habitat: ["Woodland", "Urban", "Gardens"],
                migration: "Resident",
                description: "Iconic brood parasite known for its loud ascending 'ku-oo' calls. Males are glossy black, females brown with white spots.",
                soundProfile: { clarity: "Very High", dominantFreq: "0.5-4 kHz", callPattern: "Ascending 'ku-oo' repeated at increasing pitch", noiseLevel: "High", bestTime: "Night & Dawn" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Asian%20Koel/main.png`,
                soundUrl: "https://xeno-canto.org/1071405/download",
                callTypes: ["song", "call"],
                frequencyRange: "0.5-4 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.1046/j.1474-919X.2003.00163.x",
                soibPriority: "Low",
                longTermTrend: "Moderate Increase"
        },
        {
                id: 6,
                commonName: "Coppersmith Barbet",
                scientificName: "Psilopogon haemacephalus",
                family: "Megalaimidae",
                order: "Piciformes",
                conservationStatus: "N/A",
                habitat: ["Woodland", "Gardens", "Urban"],
                migration: "Resident",
                description: "Named for its metronomic 'tuk-tuk-tuk' call that sounds like a coppersmith striking metal.",
                soundProfile: { clarity: "Very High", dominantFreq: "1-5 kHz", callPattern: "Monotonous 'tuk-tuk-tuk' repeated 50+ times per minute", noiseLevel: "Low", bestTime: "Morning" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Coppersmith%20Barbet/ML100312651.jpg`,
                soundUrl: "https://xeno-canto.org/964127/download",
                callTypes: ["song", "call"],
                frequencyRange: "1-5 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.1007/s10336-009-0399-7",
                soibPriority: "Low",
                longTermTrend: "Stable"
        },
        {
                id: 7,
                commonName: "Indian Robin",
                scientificName: "Copsychus fulicatus",
                family: "Muscicapidae",
                order: "Passeriformes",
                conservationStatus: "N/A",
                habitat: ["Scrub", "Gardens", "Rocky areas"],
                migration: "Resident",
                description: "Small insectivorous bird often seen cocking its tail upright. Males are glossy black with rusty undertail.",
                soundProfile: { clarity: "High", dominantFreq: "2-7 kHz", callPattern: "Warbling song from exposed perches", noiseLevel: "Moderate", bestTime: "Dawn & Dusk" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Indian%20Robin/main.png`,
                soundUrl: "https://xeno-canto.org/979917/download",
                callTypes: ["song", "call", "alarm"],
                frequencyRange: "2-7 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.2307/4089200",
                soibPriority: "Low",
                longTermTrend: "Stable"
        },
        {
                id: 8,
                commonName: "Oriental Magpie-Robin",
                scientificName: "Copsychus saularis",
                family: "Muscicapidae",
                order: "Passeriformes",
                conservationStatus: "N/A",
                habitat: ["Gardens", "Forest edge", "Urban"],
                migration: "Resident",
                description: "South Asia's most melodious singers. Black and white plumage with long tail frequently fanned.",
                soundProfile: { clarity: "Very High", dominantFreq: "1-8 kHz", callPattern: "Rich, varied whistling song with mimicry", noiseLevel: "Moderate", bestTime: "Dawn chorus" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Oriental%20Magpie-Robin/main.png`,
                soundUrl: "https://xeno-canto.org/1073327/download",
                callTypes: ["song", "call", "alarm"],
                frequencyRange: "1-8 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.1111/j.1474-919X.2006.00627.x",
                soibPriority: "N/A",
                longTermTrend: "N/A"
        },
        {
                id: 9,
                commonName: "Common Myna",
                scientificName: "Acridotheres tristis",
                family: "Sturnidae",
                order: "Passeriformes",
                conservationStatus: "N/A",
                habitat: ["Urban", "Agricultural", "Grassland"],
                migration: "Resident",
                description: "Bold, omnivorous bird highly adapted to human habitation.",
                soundProfile: { clarity: "Medium", dominantFreq: "0.5-5 kHz", callPattern: "Loud, varied squawks and whistles", noiseLevel: "High", bestTime: "All day" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Common%20Myna/ML101876201.jpg`,
                soundUrl: "https://xeno-canto.org/942408/download",
                callTypes: ["call", "song", "alarm"],
                frequencyRange: "0.5-5 kHz",
                regions: ["Pan-India"],
                researchDOI: "10.1111/ddi.12189",
                soibPriority: "Low",
                longTermTrend: "Stable"
        },
        {
                id: 10,
                commonName: "Rose-ringed Parakeet",
                scientificName: "Psittacula krameri",
                family: "Psittaculidae",
                order: "Psittaciformes",
                conservationStatus: "Least Concern",
                habitat: ["Urban", "Forest", "Agricultural"],
                migration: "Resident",
                description: "Bright green parakeet with distinctive rose-pink collar ring in males. Gregarious and noisy.",
                soundProfile: { clarity: "High", dominantFreq: "1-6 kHz", callPattern: "Loud screeching 'kee-ak' in flight", noiseLevel: "Very High", bestTime: "Morning & Evening" },
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Rose-ringed%20Parakeet/main.png`,
                soundUrl: "https://xeno-canto.org/1078743/download", // Placeholder sound
                regions: ["Pan-India"],
                longTermTrend: "Stable",
                soibPriority: "Low"
        },
        {
                id: 11,
                commonName: "Green Bee-eater",
                scientificName: "Merops orientalis",
                family: "Meropidae",
                order: "Coraciiformes",
                conservationStatus: "Least Concern",
                habitat: ["Scrub", "Agricultural", "Gardens"],
                migration: "Resident",
                description: "Exquisite slender bird with bronze-green plumage and elongated central tail feathers. Expert aerial hunter of bees and dragonflies.",
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Asian%20Green%20Bee-Eater/ML100845971.jpg`,
                regions: ["Pan-India"],
                soundUrl: "https://xeno-canto.org/881011/download",
                soibPriority: "Low"
        },
        {
                id: 12,
                commonName: "White-throated Kingfisher",
                scientificName: "Halcyon smyrnensis",
                family: "Alcedinidae",
                order: "Coraciiformes",
                conservationStatus: "Least Concern",
                habitat: ["Wetlands", "Agricultural", "Urban"],
                migration: "Resident",
                description: "Bright blue back and wings, chocolate brown head and breast, and a striking white throat. Often found far from water.",
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/White-Breasted%20Kingfisher/ML100151041.jpg`,
                regions: ["Pan-India"],
                soundUrl: "https://xeno-canto.org/991849/download",
                soibPriority: "Low"
        },
        {
                id: 13,
                commonName: "Cattle Egret",
                scientificName: "Bubulcus ibis",
                family: "Ardeidae",
                order: "Pelecaniformes",
                conservationStatus: "Least Concern",
                habitat: ["Agricultural", "Wetlands"],
                migration: "Resident",
                description: "Compact white egret often seen following grazing livestock to catch disturbed insects. Develops orange-buff plumes during breeding.",
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Cattle%20Egret/ML102615511.jpg`,
                regions: ["Pan-India"],
                soundUrl: "https://xeno-canto.org/1036890/download",
                soibPriority: "Low"
        },
        {
                id: 14,
                commonName: "Hoopoe",
                scientificName: "Upupa epops",
                family: "Upupidae",
                order: "Bucerotiformes",
                conservationStatus: "Least Concern",
                habitat: ["Open forest", "Gardens", "Agricultural"],
                migration: "Resident",
                description: "Iconic bird with a spectacular erectile crest, broad black-and-white barred wings, and a long curved bill for probing soil.",
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Hoopoe/ML100106251.jpg`,
                regions: ["Pan-India"],
                soundUrl: "https://xeno-canto.org/1083857/download",
                soibPriority: "Low"
        },
        {
                id: 15,
                commonName: "Indian Roller",
                scientificName: "Coracias benghalensis",
                family: "Coraciidae",
                order: "Coraciiformes",
                conservationStatus: "Least Concern",
                habitat: ["Open scrub", "Agricultural"],
                migration: "Resident",
                description: "Famous for its brilliant display of blue shades in flight. Often perched on roadside wires, it is a flagship species of the Indian countryside.",
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Indian%20Roller/ML101880891.jpg`,
                regions: ["Pan-India", "Deccan Plateau"],
                soundUrl: "https://xeno-canto.org/1059689/download",
                soibPriority: "Low"
        },
        {
                id: 16,
                commonName: "Jungle Babbler",
                scientificName: "Argya striata",
                family: "Leiothrichidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Scrub", "Gardens", "Agricultural"],
                migration: "Resident",
                description: "Gregarious bird known as the 'Seven Sisters' for their tendency to forage in noisy groups. Pale yellow eyes give them a constant 'angry' look.",
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Jungle%20Babbler/ML101450601.jpg`,
                regions: ["Pan-India"],
                soundUrl: "https://xeno-canto.org/979545/download",
                soibPriority: "Low"
        },
        {
                id: 17,
                commonName: "Brown-Headed Barbet",
                scientificName: "Psilopogon zeylanicus",
                family: "Megalaimidae",
                order: "Piciformes",
                conservationStatus: "Least Concern",
                habitat: ["Urban", "Forest", "Gardens"],
                migration: "Resident",
                description: "A large green barbet with a brown head and a distinctive yellow eye patch. Its loud, repetitive call is a signature sound of Indian summers.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Brown-Headed%20Barbet/ML101410271.jpg`,
                soundUrl: "https://xeno-canto.org/808586/download",
                soibPriority: "Low"
        },
        {
                id: 18,
                commonName: "Common Kingfisher",
                scientificName: "Alcedo atthis",
                family: "Alcedinidae",
                order: "Coraciiformes",
                conservationStatus: "Least Concern",
                habitat: ["Wetlands", "Rivers", "Lakes"],
                migration: "Resident/Local Migrant",
                description: "Small blue-and-orange kingfisher known for its lightning-fast dives. It is a widespread sentinel of healthy freshwater ecosystems.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Common%20Kingfisher/ML102292211.jpg`,
                soundUrl: "https://xeno-canto.org/sounds/uploaded/XPZUAKLNCX/XC737010.mp3",
                soibPriority: "Low"
        },
        {
                id: 19,
                commonName: "Common Rosefinch",
                scientificName: "Carpodacus erythrinus",
                family: "Fringillidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Scrub", "Forest", "Agricultural"],
                migration: "Migratory-Local",
                description: "Males have a beautiful rose-red head and breast. They are often found in high-altitude scrub during breeding and migrate to plains in winter.",
                regions: ["Himalayas", "Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Common%20Rosefinch/ML101683671.jpg`,
                soundUrl: "https://xeno-canto.org/1054636/download",
                soibPriority: "Low"
        },
        {
                id: 20,
                commonName: "Common Tailorbird",
                scientificName: "Orthotomus sutorius",
                family: "Cisticolidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Gardens", "Urban", "Forest edge"],
                migration: "Resident",
                description: "Famous for 'sewing' large leaves together to create a nest. A tiny, loud, and active bird common in urban gardens.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Common%20Tailorbird/ML100767561.jpg`,
                soundUrl: "https://xeno-canto.org/950021/download",
                soibPriority: "Low"
        },
        {
                id: 21,
                commonName: "Forest Wagtail",
                scientificName: "Dendronanthus indicus",
                family: "Motacillidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Forest", "Woodland"],
                migration: "Migratory-Long-Distance",
                description: "Unlike other wagtails, it swings its tail sideways. It has a distinctive double black breast band and is a shy forest dweller.",
                regions: ["Pan-India", "Northeast"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Forest%20Wagtail/ML100072911.jpg`,
                soundUrl: "https://xeno-canto.org/838777/download",
                soibPriority: "High"
        },
        {
                id: 22,
                commonName: "Gray Wagtail",
                scientificName: "Motacilla cinerea",
                family: "Motacillidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Hill streams", "Rivers"],
                migration: "Migratory-Local",
                description: "Slender wagtail with a very long tail. Despite the name, it has a bright yellow vent and underparts during the breeding season.",
                regions: ["Pan-India", "Himalayas"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Gray%20Wagtail/ML100275401.jpg`,
                soundUrl: "https://xeno-canto.org/1083126/download",
                soibPriority: "Low"
        },
        {
                id: 23,
                commonName: "Indian Grey Hornbill",
                scientificName: "Ocyceros birostris",
                family: "Bucerotidae",
                order: "Bucerotiformes",
                conservationStatus: "Least Concern",
                habitat: ["Urban", "Woodland", "Gardens"],
                migration: "Resident",
                description: "A large grey bird with a curved bill and a small casque. Frequently seen in urban areas with old fruiting trees.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Indian%20Grey%20Hornbill/ML100607991.jpg`,
                soundUrl: "https://xeno-canto.org/585628/download",
                soibPriority: "Low"
        },
        {
                id: 24,
                commonName: "Indian Pitta",
                scientificName: "Pitta brachyura",
                family: "Pittidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Forest", "Dense scrub"],
                migration: "Migratory-Local",
                description: "A stunning multi-colored bird known as the 'Naurang' (nine colors). It is a shy ground-dweller that migrates across the subcontinent.",
                regions: ["Pan-India", "Western Ghats"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Indian%20Pitta/ML100080251.jpg`,
                soundUrl: "https://xeno-canto.org/648161/download",
                soibPriority: "Low"
        },
        {
                id: 25,
                commonName: "Northern Lapwing",
                scientificName: "Vanellus vanellus",
                family: "Charadriidae",
                order: "Charadriiformes",
                conservationStatus: "Near Threatened",
                habitat: ["Wetlands", "Agricultural"],
                migration: "Migratory-Long-Distance",
                description: "Distinctive crested lapwing with iridescent green plumage on the back. A winter visitor to northern India.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Northern%20Lapwing/ML102222881.jpg`,
                soundUrl: "https://xeno-canto.org/1023873/download",
                soibPriority: "Medium"
        },
        {
                id: 26,
                commonName: "Red-Wattled Lapwing",
                scientificName: "Vanellus indicus",
                family: "Charadriidae",
                order: "Charadriiformes",
                conservationStatus: "Least Concern",
                habitat: ["Wetlands", "Agricultural", "Open ground"],
                migration: "Resident",
                description: "Known for its loud 'did-he-do-it' alarm call. Has a distinctive red wattle in front of the eyes.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Red-Wattled%20Lapwing/ML101449691.jpg`,
                soundUrl: "https://xeno-canto.org/1073292/download",
                soibPriority: "Low"
        },
        {
                id: 27,
                commonName: "Ruddy Shelduck",
                scientificName: "Tadorna ferruginea",
                family: "Anatidae",
                order: "Anseriformes",
                conservationStatus: "Least Concern",
                habitat: ["Lakes", "Rivers", "Wetlands"],
                migration: "Migratory-Local",
                description: "A distinctive orange-brown duck with a pale head. It is a common winter visitor to Indian wetlands.",
                regions: ["Pan-India", "Himalayas"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Ruddy%20Shelduck/ML102015981.jpg`,
                soundUrl: "https://xeno-canto.org/1045752/download",
                soibPriority: "Low"
        },
        {
                id: 28,
                commonName: "Rufous Treepie",
                scientificName: "Dendrocitta vagabunda",
                family: "Corvidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Woodland", "Forest border", "Urban"],
                migration: "Resident",
                description: "A long-tailed corvid with rufous, grey, and black plumage. Known for its loud, metallic calls and aggressive nature.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Rufous%20Treepie/ML103677381.jpg`,
                soundUrl: "https://xeno-canto.org/980123/download",
                soibPriority: "Low"
        },
        {
                id: 29,
                commonName: "Sarus Crane",
                scientificName: "Antigone antigone",
                family: "Gruidae",
                order: "Gruiformes",
                conservationStatus: "Vulnerable",
                habitat: ["Wetlands", "Agricultural"],
                migration: "Resident",
                description: "The world's tallest flying bird. Known for lifelong pair-bonding and elaborate coordinated dances.",
                regions: ["Pan-India", "Central India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/Sarus%20Crane/ML103190291.jpg`,
                soundUrl: "https://xeno-canto.org/954263/download",
                soibPriority: "High"
        },
        {
                id: 30,
                commonName: "White Wagtail",
                scientificName: "Motacilla alba",
                family: "Motacillidae",
                order: "Passeriformes",
                conservationStatus: "Least Concern",
                habitat: ["Rivers", "Wetlands", "Agricultural"],
                migration: "Migratory-Long-Distance",
                description: "A striking black-and-white wagtail that is a common winter visitor. Often seen near water or on open grass.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/White%20Wagtail/ML103013411.jpg`,
                soundUrl: "https://xeno-canto.org/990630/download",
                soibPriority: "Low"
        },
        {
                id: 31,
                commonName: "White-Breasted Waterhen",
                scientificName: "Amaurornis phoenicurus",
                family: "Rallidae",
                order: "Gruiformes",
                conservationStatus: "Least Concern",
                habitat: ["Wetlands", "Dense vegetation", "Gardens"],
                migration: "Resident",
                description: "A common marsh bird with a white face and breast and a red undertail. Known for its loud, croaking calls in monsoon.",
                regions: ["Pan-India"],
                image: `${import.meta.env.VITE_API_BASE_URL || ""}/api/assets/images/White-Breasted%20Waterhen/ML100908141.jpg`,
                soundUrl: "https://xeno-canto.org/1031057/download",
                soibPriority: "Low"
        }
];

export const conservationStatusMap = {
        "LC": { label: "Least Concern", color: "#3b82f6", bg: "bg-blue-500/10", text: "text-blue-400", border: "border-blue-500/30" },
        "NT": { label: "Near Threatened", color: "#eab308", bg: "bg-yellow-500/10", text: "text-yellow-400", border: "border-yellow-500/30" },
        "VU": { label: "Vulnerable", color: "#f97316", bg: "bg-orange-500/10", text: "text-orange-400", border: "border-orange-500/30" },
        "CR": { label: "Critically Endangered", color: "#dc2626", bg: "bg-red-600/10", text: "text-red-500", border: "border-red-600/30" }
};

export const habitatTypes = ["All", "Forest", "Urban", "Wetland", "Scrub", "Agricultural", "Coastal", "Grassland", "Himalayan", "Desert"];

export const regionsList = ["All", "Pan-India", "Western Ghats", "Himalayas", "Northeast", "Coastal India", "Andaman & Nicobar", "Central India", "Deccan Plateau"];

export default indianBirds;
